# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
        
      - name: Git relation
        run: |
          echo ${{ github.event.pull_request.base.ref }}
          echo ${{ github.event.pull_request.base.sha }}

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          go run main.go
          # if [[ go run main.go ]]; then echo 1; else echo 0; fi
      - name: Correct
        run: |
          echo 222
      - name: Notify Test Failed
        if: ${{ failure() }}
        run: |
          curl -H "Content-Type: application/json" 
          -d '{"msg_type": "interactive","card":{"config":{"wide_screen_mode":true},"i18n_elements":{"zh_cn":[{"tag":"div","text":{"tag":"lark_md","content":"**Deploy Result:** ggg "}},{"tag":"div","text":{"tag":"lark_md","content":"**Env:** ggg"}},{"tag":"div","text":{"tag":"lark_md","content":"**Job_name:** ggg"}},{"tag":"div","text":{"tag":"lark_md","content":"**Tag**: ${tag}"}},{"tag":"div","text":{"tag":"lark_md","content":"**CommitMsg**: ggg"}},{"tag":"div","text":{"tag":"lark_md","content":"**Reason**: ggg"}}]}}}' 
          https://open.feishu.cn/open-apis/bot/v2/hook/54770642-1fba-4443-b28d-095de72c1414

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Test Deploy
        run: |
           echo xxx
          
